/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProcessPdfRouteImport } from './routes/api/process-pdf'
import { Route as ApiTranslatePdfRouteImport } from './routes/api/translate-pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessPdfRoute = ApiProcessPdfRouteImport.update({
  id: '/api/process-pdf',
  path: '/api/process-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslatePdfRoute = ApiTranslatePdfRouteImport.update({
  id: '/api/translate-pdf',
  path: '/api/translate-pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/process-pdf': typeof ApiProcessPdfRoute
  '/api/translate-pdf': typeof ApiTranslatePdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/process-pdf': typeof ApiProcessPdfRoute
  '/api/translate-pdf': typeof ApiTranslatePdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/process-pdf': typeof ApiProcessPdfRoute
  '/api/translate-pdf': typeof ApiTranslatePdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/process-pdf' | '/api/translate-pdf'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/process-pdf' | '/api/translate-pdf'
  id: '__root__' | '/' | '/api/process-pdf' | '/api/translate-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiProcessPdfRoute: typeof ApiProcessPdfRoute
  ApiTranslatePdfRoute: typeof ApiTranslatePdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process-pdf': {
      id: '/api/process-pdf'
      path: '/api/process-pdf'
      fullPath: '/api/process-pdf'
      preLoaderRoute: typeof ApiProcessPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate-pdf': {
      id: '/api/translate-pdf'
      path: '/api/translate-pdf'
      fullPath: '/api/translate-pdf'
      preLoaderRoute: typeof ApiTranslatePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiProcessPdfRoute: ApiProcessPdfRoute,
  ApiTranslatePdfRoute: ApiTranslatePdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
